package de.jonasrotert.stammbaum.api.domain;

public enum PersonEventType
{
    ADOPTION, ARRIVAL, BAPTISM, BAR_MITZVAH, BAS_MITZVAH, BIRTH, BLESSING, BURIAL, CENSUS, CHRISTENING, CHRISTENING_ADULT, CONFIRMATION, CREMATION, DEATH, EMIGRATION, EVENT, FIRST_COMMUNION, GRADUATION, IMMIGRATION, NATURALIZATION, ORDINATION, PROBATE, RETIREMENT, WILL;
}
